[package]
name = "nip-70"
version = "0.4.3"
edition = "2021"
license = "MIT"
description = "Reference implementation of Nostr NIP-70"
documentation = "https://docs.rs/nip-70"
repository = "https://github.com/tvolk131/nip-70"

[dependencies]
anyhow = "1"
async-trait = "0.1"
futures = "0.3.30"
lightning-invoice = "0.29.0"
nostr-sdk = "0.27"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["io-util", "net", "rt"] }

[dev-dependencies]
bitcoin_hashes = "0.12.0"
lazy_static = "1"
