[package]
name = "nip-70"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Reference implementation of Nostr NIP-70"
documentation = "https://docs.rs/nip-70"
repository = "https://github.com/tvolk131/nip-70"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
nostr-sdk = "0.27.0"
serde = "1.0.196"
serde_json = "1.0.113"
tokio = { version = "1.35.1", features = ["io-util", "net", "rt"] }

[dev-dependencies]
lazy_static = "1.4.0"
